on:
  push:
    branches:
      - main

jobs:
  start_server:
    runs-on: ubuntu-latest

    name: start server
    steps:
      - uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'oracle'
          java-package: 'jdk'


      - uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'


      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: '$(date-1)-nightly'
          path: ./world/*
        if: ${{ env.CURRENT_TIME <= '15:05:00' }}
 
      - uses: actions/download-artifact@v4
        with:
          name: '$(date)-daily'
          path: ./world/*
        if: ${{ env.CURRENT_TIME > '15:05:00' }}

      - run: hostname -i
      - run: hostname -I
      - run: ip addr show
      - run: sudo ufw enable
      - run: sudo ufw allow 22069/tcp
      - run: sudo ufw allow 22069/udp
      
      - run: python app.py

        
      - uses: actions/upload-artifact@v4
        with:
          name: '$(date)-daily'
          path: ./world/*
        if: ${{ env.CURRENT_TIME <= '15:05:00' }}

      - uses: actions/upload-artifact@v4
        with:
          name: '$(date)-nightly'
          path: ./world/*
        if: ${{ env.CURRENT_TIME > '20:00:00' }}
